import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import ConvexClientProvider from "@/providers/ConvexClientProvider";
import ModalProvider from "@/providers/ModalProvider";
import CheckScreen from "@/components/features/CheckScreen";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <CheckScreen>{children}</CheckScreen>
          <ModalProvider />
          <Toaster position="top-center" />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
